### ISSUE TITLE
NPM package seems not to be published.

### ISSUE THREAD

**Issue by bernatvadell** [react-native-community/react-native-progress-bar-android#2]
Hi!

I am not finding the react-native-androidprogressbar package in the NPM repository.

Is it possible that the package has not yet been published in the repository?

Thx!

**Comment by Naturalclar** [comment]
any updates on this?

**Comment by Naturalclar** [comment]
@cpojer 
If this package is in need for a maintainer to publish the package, I'd like to volunteer to be a maintainer. Would that be possible? :)

**Comment by cpojer** [comment]
That sounds great! Could you send me your npm username to cpojer@fb.com?

**Comment by Naturalclar** [comment]
@cpojer 
Thanks! I just sent the email to you with my npm username :)

**Comment by Naturalclar** [comment]
Successfully published this package :tada:
